apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: sysbench-vpa
spec:
  recommenders:
    - name: clever
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sysbench
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
        maxAllowed:
          cpu: 16
        controlledResources: ["cpu"]