{
 "title": "Clever VPA Recommender",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_frequency_max_hertz, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Frequency (Max of all CPUs) for Node $node",
   "type": "timeseries",
   "description": "For the node with more than 1 CPU, choose the maximum frequency.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max(node_cpu_scaling_frequency_hertz{instance=\"$node\"})",
     "legendFormat": "Current CPU Frequency "
    },
    {
     "expr": "max(node_cpu_frequency_max_hertz{instance=\"$node\"})",
     "legendFormat": "Max CPU Frequency"
    },
    {
     "expr": "max(node_cpu_frequency_min_hertz{instance=\"$node\"})",
     "legendFormat": "Min CPU Frequency"
    }
   ]
  },
  {
   "title": "Managed Container CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(container) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"$container\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Actual IPS (Instructions/second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(pod_cpu_instructions{pod_namespace=\"$namespace\"} / 3)",
     "legendFormat": "sysbench"
    }
   ]
  }
 ]
}